services:
  store:
    build:
      context: .
      args:
        - DEV=true
    ports: 
      - "8000:8000"
    volumes:
      - ./store:/store
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEBUG=1
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    expose:
      - 5432


volumes:
  dev-db-data: