services:
  store:
    build:
      context: .
      args:
        - DEV=true
    ports: 
      - "8000:8000"
    volumes:
      - ./store:/store
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - db

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - ./.env

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env


volumes:
  dev-db-data: